# Generated by Django 5.0.2 on 2024-02-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='uf',
            field=models.CharField(max_length=20, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.CharField(choices=[('ASIA', 'Ásia'), ('AMERICA', 'América'), ('AFRICA', 'África'), ('EUROPA', 'Europa'), ('OCEANIA', 'Oceania'), ('ANTÁRTIDA', 'Antártida')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comuns.estado')),
            ],
        ),
    ]
