# Generated by Django 5.0.3 on 2024-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('min_age', models.PositiveIntegerField(default=12)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
