version: "3.1"

services:
  mongo:
    image: mongo
    container_name: my_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_DATABASE: my_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
