version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
