# Generated by Django 5.0.2 on 2024-02-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.PositiveIntegerField(help_text='ano que o clube foi criado', verbose_name='Ano Fundação'),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.clube')),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
