# Generated by Django 5.0.2 on 2024-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_alter_clube_options_alter_clube_divisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='camisa',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº da camisa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Não informar')], default='N', max_length=128),
        ),
    ]
